# Generated by Django 3.0.3 on 2020-02-11 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, help_text='Enter a brief description of the assignment', max_length=1000),
            preserve_default=False,
        ),
    ]
