# Generated by Django 3.0.3 on 2020-02-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_assignment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Unit',
            new_name='unit',
        ),
    ]
